     
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        encrypt:
            enabled: false
        git: 
          uri:  https://github.com/Relesi/config-repo.git
          search-paths: provider, store, carrier
          
          
          
          
          